version: "3.3"

services:
  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: achatdb
      MYSQL_USER: root
      MYSQL_PASSWORD:
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3307:3307
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    image:  spicymgws/jenkins-docker:102
    restart: on-failure
    ports:
      - 8089:8089
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/achatdb?useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db: